from __future__ import annotations

from .model import (
    QuotaMetric,
    ResourceDescriptor,
    ResourceHealth,
    ResourceRegistry,
    UsageClass,
)

_VERIFIED_AT = "2026-09-22"
_DEV = (UsageClass.DEVELOPMENT, UsageClass.PROTOTYPING)
_DEV_PERSONAL = (
    UsageClass.PERSONAL,
    UsageClass.DEVELOPMENT,
    UsageClass.PROTOTYPING,
)


def free_resource_pool_v1() -> ResourceRegistry:
    """Return the verified static catalog for Free Resource Pool V1.

    All remote resources intentionally start UNKNOWN. An authenticated health
    adapter must prove runtime availability before the router may select them.
    Static catalog metadata describes documented free access, not the user's
    current account balance, credentials or live quota.
    """

    resources = (
        ResourceDescriptor(
            resource_id="openrouter_free_pool",
            provider="OpenRouter",
            capabilities=(
                "llm.general",
                "llm.reasoning",
                "llm.coding",
                "llm.review",
            ),
            free_tier=True,
            quota=(
                QuotaMetric(
                    name="requests",
                    limit=50,
                    remaining=None,
                    unit="requests/day",
                    reset_period="daily",
                    source="provider_pricing",
                ),
            ),
            rate_limit=("50 requests/day on the documented Free plan",),
            reset_period="daily",
            availability="account_and_model_dependent",
            latency="model_dependent",
            auth_required=True,
            commercial_use="model_terms_dependent",
            privacy="provider_and_model_dependent",
            supported_models=("openrouter/free",),
            health=ResourceHealth.UNKNOWN,
            last_checked=_VERIFIED_AT,
            replacement_candidates=(
                "groq_free",
                "nvidia_nim_developer",
                "mistral_free_mode",
            ),
            priority={
                "llm.general": 20,
                "llm.reasoning": 20,
                "llm.coding": 20,
                "llm.review": 20,
            },
            usage_classes=_DEV_PERSONAL,
            documentation_urls=(
                "https://openrouter.ai/docs/features/model-routing",
                "https://openrouter.ai/openrouter/free",
            ),
            terms_urls=("https://openrouter.ai/terms",),
            notes=(
                "Free model inventory can change.",
                "Commercial eligibility must be checked against the selected model terms.",
            ),
        ),
        ResourceDescriptor(
            resource_id="groq_free",
            provider="Groq",
            capabilities=(
                "llm.general",
                "llm.reasoning",
                "llm.coding",
                "llm.review",
            ),
            free_tier=True,
            quota=(
                QuotaMetric(
                    name="qwen_qwen3_8_27b_requests",
                    limit=1000,
                    remaining=None,
                    unit="requests/day",
                    reset_period="daily",
                    source="provider_rate_limits",
                ),
                QuotaMetric(
                    name="qwen_qwen3_8_27b_tokens",
                    limit=200000,
                    remaining=None,
                    unit="tokens/day",
                    reset_period="daily",
                    source="provider_rate_limits",
                ),
            ),
            rate_limit=(
                "qwen/qwen3.8-27b: 30 requests/minute",
                "qwen/qwen3.8-27b: 8000 tokens/minute",
            ),
            reset_period="provider_defined",
            availability="account_dependent_free_access",
            latency="low",
            auth_required=True,
            commercial_use="requires_provider_and_model_terms_review",
            privacy="third_party",
            context_window=None,
            supported_models=("qwen/qwen3.8-27b",),
            health=ResourceHealth.UNKNOWN,
            last_checked=_VERIFIED_AT,
            replacement_candidates=(
                "openrouter_free_pool",
                "nvidia_nim_developer",
                "mistral_free_mode",
            ),
            priority={
                "llm.general": 15,
                "llm.reasoning": 15,
                "llm.coding": 15,
                "llm.review": 15,
            },
            usage_classes=_DEV_PERSONAL,
            documentation_urls=(
                "https://console.groq.com/docs/rate-limits",
                "https://console.groq.com/docs/overview",
            ),
            terms_urls=("https://groq.com/terms-of-use/",),
            notes=(
                "Free access is account dependent; provider name alone does not prove a free next request.",
                "Live organization limits must be read from the authenticated account when possible.",
            ),
        ),
        ResourceDescriptor(
            resource_id="nvidia_nim_developer",
            provider="NVIDIA",
            capabilities=(
                "llm.general",
                "llm.reasoning",
                "llm.coding",
                "llm.review",
            ),
            free_tier=True,
            availability="developer_program",
            latency="provider_managed",
            auth_required=True,
            commercial_use="production_requires_nvidia_ai_enterprise",
            development_only=True,
            privacy="third_party",
            supported_models=("nvidia/nemotron-3-ultra-550b-a55b",),
            health=ResourceHealth.UNKNOWN,
            last_checked=_VERIFIED_AT,
            replacement_candidates=(
                "groq_free",
                "openrouter_free_pool",
                "mistral_free_mode",
            ),
            priority={
                "llm.general": 25,
                "llm.reasoning": 10,
                "llm.coding": 10,
                "llm.review": 10,
            },
            usage_classes=_DEV,
            documentation_urls=(
                "https://developer.nvidia.com/nim",
                "https://docs.nvidia.com/nim/",
            ),
            terms_urls=(
                "https://developer.nvidia.com/nvidia-api-trial-terms-of-service",
            ),
            notes=(
                "Treat free hosted endpoints as development/prototyping resources.",
                "Do not silently promote this resource to production use.",
            ),
        ),
        ResourceDescriptor(
            resource_id="mistral_free_mode",
            provider="Mistral AI",
            capabilities=(
                "llm.general",
                "llm.reasoning",
                "llm.coding",
                "llm.review",
            ),
            free_tier=True,
            quota=(
                QuotaMetric(
                    name="included_api_credit",
                    limit=10,
                    remaining=None,
                    unit="USD_credit/month",
                    reset_period="monthly",
                    source="provider_pricing",
                ),
            ),
            reset_period="monthly",
            availability="account_dependent_free_mode",
            latency="provider_managed",
            auth_required=True,
            commercial_use="not_assumed_for_auto_routing",
            privacy="third_party",
            supported_models=("mistral-small-latest",),
            health=ResourceHealth.UNKNOWN,
            last_checked=_VERIFIED_AT,
            replacement_candidates=(
                "groq_free",
                "openrouter_free_pool",
                "nvidia_nim_developer",
            ),
            priority={
                "llm.general": 30,
                "llm.reasoning": 30,
                "llm.coding": 30,
                "llm.review": 30,
            },
            usage_classes=_DEV_PERSONAL,
            documentation_urls=(
                "https://mistral.ai/pricing",
                "https://help.mistral.ai/en/articles/347464-how-do-api-rate-limits-work",
            ),
            terms_urls=("https://mistral.ai/terms",),
            notes=(
                "Free mode is account dependent and must hard-stop before pay-as-you-go usage.",
                "Live remaining credit is runtime state, not static catalog metadata.",
            ),
        ),
        ResourceDescriptor(
            resource_id="github_actions_standard",
            provider="GitHub",
            capabilities=(
                "build.web",
                "build.android",
                "build.windows",
                "build.linux",
                "build.macos",
                "workflow.ci",
                "artifact.build",
            ),
            free_tier=True,
            quota=(
                QuotaMetric(
                    name="private_repo_minutes",
                    limit=2000,
                    remaining=None,
                    unit="minutes/month",
                    reset_period="monthly",
                    source="github_free_plan",
                ),
                QuotaMetric(
                    name="artifact_storage",
                    limit=500,
                    remaining=None,
                    unit="MB",
                    reset_period="billing_cycle",
                    source="github_free_plan",
                ),
            ),
            reset_period="monthly",
            availability="repository_and_plan_dependent",
            latency="queue_dependent",
            auth_required=True,
            commercial_use="plan_and_repository_terms_apply",
            privacy="repository_and_runner_dependent",
            max_runtime="workflow/job limits apply",
            compute="standard_github_hosted_or_self_hosted_runner",
            storage="500 MB artifact storage on GitHub Free private repositories",
            health=ResourceHealth.UNKNOWN,
            last_checked=_VERIFIED_AT,
            replacement_candidates=("future_local_runner",),
            priority={
                "build.web": 10,
                "build.android": 10,
                "build.windows": 10,
                "build.linux": 10,
                "build.macos": 10,
                "workflow.ci": 10,
                "artifact.build": 10,
            },
            usage_classes=_DEV,
            documentation_urls=(
                "https://docs.github.com/billing/managing-billing-for-your-products/managing-billing-for-github-actions/about-billing-for-github-actions",
            ),
            terms_urls=("https://docs.github.com/site-policy/github-terms/github-terms-of-service",),
            notes=(
                "Standard GitHub-hosted runners are free for public repositories.",
                "Larger runners are not treated as free resources.",
            ),
        ),
        ResourceDescriptor(
            resource_id="supabase_free",
            provider="Supabase",
            capabilities=(
                "memory.read",
                "memory.write",
                "database.postgres",
                "storage.artifact",
                "queue.realtime",
            ),
            free_tier=True,
            quota=(
                QuotaMetric(
                    name="database_size",
                    limit=500,
                    remaining=None,
                    unit="MB/project",
                    source="provider_pricing",
                ),
                QuotaMetric(
                    name="file_storage",
                    limit=1,
                    remaining=None,
                    unit="GB",
                    source="provider_pricing",
                ),
                QuotaMetric(
                    name="egress",
                    limit=5,
                    remaining=None,
                    unit="GB/month",
                    reset_period="monthly",
                    source="provider_pricing",
                ),
                QuotaMetric(
                    name="edge_function_invocations",
                    limit=500000,
                    remaining=None,
                    unit="invocations/month",
                    reset_period="monthly",
                    source="provider_billing_docs",
                ),
            ),
            reset_period="monthly",
            availability="project_and_account_dependent",
            latency="region_dependent",
            auth_required=True,
            commercial_use="provider_terms_apply",
            privacy="third_party_database",
            memory="500 MB shared RAM on Free plan",
            storage="500 MB database and 1 GB file storage",
            health=ResourceHealth.UNKNOWN,
            last_checked=_VERIFIED_AT,
            replacement_candidates=("local_memory_backend", "future_nas_backend"),
            priority={
                "memory.read": 20,
                "memory.write": 20,
                "database.postgres": 10,
                "storage.artifact": 30,
                "queue.realtime": 20,
            },
            usage_classes=_DEV,
            documentation_urls=(
                "https://supabase.com/pricing",
                "https://supabase.com/docs/guides/platform/manage-your-usage",
            ),
            terms_urls=("https://supabase.com/terms",),
            notes=(
                "Free projects may pause after inactivity.",
                "Memory Fabric must never make Supabase the only authoritative memory node.",
            ),
        ),
        ResourceDescriptor(
            resource_id="cloudflare_workers_free",
            provider="Cloudflare",
            capabilities=(
                "hosting.web",
                "compute.serverless",
                "gateway.http",
            ),
            free_tier=True,
            quota=(
                QuotaMetric(
                    name="requests",
                    limit=100000,
                    remaining=None,
                    unit="requests/day",
                    reset_period="daily",
                    source="workers_limits",
                ),
                QuotaMetric(
                    name="cpu_time",
                    limit=10,
                    remaining=None,
                    unit="ms/request",
                    source="workers_limits",
                ),
                QuotaMetric(
                    name="memory",
                    limit=128,
                    remaining=None,
                    unit="MB/isolate",
                    source="workers_limits",
                ),
            ),
            rate_limit=("50 subrequests/request on Free plan",),
            reset_period="daily",
            availability="account_and_deployment_dependent",
            latency="edge",
            auth_required=True,
            commercial_use="provider_terms_apply",
            privacy="edge_third_party",
            memory="128 MB per isolate",
            compute="Workers Free CPU limits",
            health=ResourceHealth.UNKNOWN,
            last_checked=_VERIFIED_AT,
            replacement_candidates=("future_secondary_host",),
            priority={
                "hosting.web": 10,
                "compute.serverless": 10,
                "gateway.http": 10,
            },
            usage_classes=_DEV,
            documentation_urls=(
                "https://developers.cloudflare.com/workers/platform/limits/",
                "https://workers.cloudflare.com/pricing/",
            ),
            terms_urls=("https://www.cloudflare.com/terms/",),
            notes=(
                "Cloudflare remains a transport/compute adapter, never an architecture dependency.",
            ),
        ),
        ResourceDescriptor(
            resource_id="inngest_hobby",
            provider="Inngest",
            capabilities=(
                "workflow.durable",
                "queue.task",
                "schedule.task",
            ),
            free_tier=True,
            quota=(
                QuotaMetric(
                    name="executions",
                    limit=50000,
                    remaining=None,
                    unit="executions/month",
                    reset_period="monthly",
                    source="provider_pricing",
                ),
                QuotaMetric(
                    name="events",
                    limit=500000,
                    remaining=None,
                    unit="events/month",
                    reset_period="monthly",
                    source="provider_pricing",
                ),
                QuotaMetric(
                    name="concurrent_steps",
                    limit=5,
                    remaining=None,
                    unit="steps",
                    source="provider_pricing",
                ),
                QuotaMetric(
                    name="queue_depth",
                    limit=100000,
                    remaining=None,
                    unit="items",
                    source="provider_pricing",
                ),
            ),
            reset_period="monthly",
            availability="account_and_service_dependent",
            latency="service_dependent",
            auth_required=True,
            commercial_use="provider_terms_apply",
            privacy="third_party_workflow_metadata",
            max_runtime="30 days; free sleeps up to 7 days",
            health=ResourceHealth.UNKNOWN,
            last_checked=_VERIFIED_AT,
            replacement_candidates=("cantiere_durable_controller",),
            priority={
                "workflow.durable": 20,
                "queue.task": 20,
                "schedule.task": 20,
            },
            usage_classes=_DEV,
            documentation_urls=(
                "https://www.inngest.com/pricing",
                "https://www.inngest.com/docs/usage-limits/inngest",
            ),
            terms_urls=("https://www.inngest.com/terms",),
            notes=(
                "Hobby quota exhaustion pauses service; no paid fallback is allowed automatically.",
                "Inngest may execute remote workflow steps but never owns Cantiere project lifecycle.",
            ),
        ),
        ResourceDescriptor(
            resource_id="posthog_free",
            provider="PostHog",
            capabilities=(
                "analytics.event",
                "diagnostics.remote",
                "feature_flag",
            ),
            free_tier=True,
            quota=(
                QuotaMetric(
                    name="product_analytics_events",
                    limit=1000000,
                    remaining=None,
                    unit="events/month",
                    reset_period="monthly",
                    source="provider_pricing",
                ),
                QuotaMetric(
                    name="session_replays",
                    limit=5000,
                    remaining=None,
                    unit="recordings/month",
                    reset_period="monthly",
                    source="provider_pricing",
                ),
                QuotaMetric(
                    name="feature_flag_requests",
                    limit=1000000,
                    remaining=None,
                    unit="requests/month",
                    reset_period="monthly",
                    source="provider_pricing",
                ),
            ),
            reset_period="monthly",
            availability="project_and_account_dependent",
            latency="remote",
            auth_required=True,
            commercial_use="provider_terms_apply",
            privacy="telemetry_only_no_prompt_text_by_default",
            health=ResourceHealth.UNKNOWN,
            last_checked=_VERIFIED_AT,
            replacement_candidates=("local_diagnostics",),
            priority={
                "analytics.event": 10,
                "diagnostics.remote": 10,
                "feature_flag": 20,
            },
            usage_classes=_DEV,
            documentation_urls=("https://posthog.com/pricing",),
            terms_urls=("https://posthog.com/terms",),
            notes=(
                "Remote telemetry is optional and must preserve the existing no-prompt-leakage policy.",
            ),
        ),
        ResourceDescriptor(
            resource_id="linear_free",
            provider="Linear",
            capabilities=("project.track",),
            free_tier=True,
            quota=(
                QuotaMetric(
                    name="issues",
                    limit=250,
                    remaining=None,
                    unit="issues/workspace",
                    source="provider_pricing",
                ),
                QuotaMetric(
                    name="teams",
                    limit=2,
                    remaining=None,
                    unit="teams/workspace",
                    source="provider_pricing",
                ),
                QuotaMetric(
                    name="file_upload",
                    limit=10,
                    remaining=None,
                    unit="MB/file",
                    source="provider_pricing",
                ),
            ),
            availability="workspace_dependent",
            latency="remote",
            auth_required=True,
            commercial_use="provider_terms_apply",
            privacy="third_party_project_metadata",
            health=ResourceHealth.UNKNOWN,
            last_checked=_VERIFIED_AT,
            replacement_candidates=("github_issues",),
            priority={"project.track": 20},
            usage_classes=_DEV,
            documentation_urls=("https://linear.app/pricing",),
            terms_urls=("https://linear.app/terms",),
            notes=(
                "Free plan includes API and webhook access.",
                "Catalog presence does not mean the Linear connector is currently installed.",
            ),
        ),
        ResourceDescriptor(
            resource_id="github_issues",
            provider="GitHub",
            capabilities=("project.track",),
            free_tier=True,
            availability="repository_dependent",
            latency="remote",
            auth_required=True,
            commercial_use="provider_terms_apply",
            privacy="repository_visibility_dependent",
            health=ResourceHealth.UNKNOWN,
            last_checked=_VERIFIED_AT,
            replacement_candidates=("linear_free",),
            priority={"project.track": 10},
            usage_classes=_DEV,
            documentation_urls=("https://docs.github.com/issues",),
            terms_urls=("https://docs.github.com/site-policy/github-terms/github-terms-of-service",),
            notes=(
                "GitHub API rate limits are runtime/account state and are not encoded as a fake static remaining quota.",
            ),
        ),
    )
    return ResourceRegistry(resources)
